#!/bin/sh
#PBS -l nodes=1:ppn=4

########### UPDATE THESE VARIABLES ###############
# the directory where your files are
pa1_home=/home/$USER/pa1/radixsort
##################################################

cd $pa1_home
echo $USER
echo $pa1_home
######### ADD YOUR EXECUTION SCRIPT HERE #########
# Set the number of threads
export OMP_NUM_THREADS=4
# Clean up the directory
make clean
# Compile the program
make
# Run radixsort
./radixsort 
